version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: bio_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9230:9200
    networks:
      - esnet
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: bio_kibana
    ports:
        - 5631:5601
    networks:
        - esnet
    depends_on:
        - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
